spring:
  # DataBase 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    # 쿼리 확인 (default: false)
    show-sql: true

    # 변수 명 그대로 사용 (자동으로 snake case 변환 방지)
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# 기동 서버 포트 설정
server:
  port: 8088

# JWT 유효시간
jwt:
  secretKey: mf93nveio49824foilmlfdmvnew9jf3k2d9
  accessToken:
    # 3 * 60 * 60 * 1000 (3 시간)
    time: 10800000
  refreshToken:
    # 24 * 60 * 60 *1000 (1 일)
    time: 86400000
